services:
  postgres:
    image: postgres:16
    container_name: cardapio-db
    environment:
      POSTGRES_DB: cardapio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: